# Possible optimizations for 8088 class processors
#
# -oa   Relax alias checking
# -ob   Try to generate straight line code
# -oe - expand user functions inline (-oe=20 is default)
# -oh   Enable repeated optimizations
# -oi   generate certain lib funcs inline
# -oi+  Set max inline depth (C++ only, use -oi for C)
# -ok   Flowing of register save into function flow graph
# -ol   loop optimizations
# -ol+  loop optimizations plus unrolling
# -or   Reorder for pipelined (486+ procs); not sure if good to use
# -os   Favor space over time
# -ot   Favor time over space
# -ei   Allocate an "int" for all enum types
# -zp2  Allow compiler to add padding to structs
# -zpw  Use with above; make sure you are warning free!
# -0    8088/8086 class code generation
# -s    disable stack overflow checking
# -zmf  put each function in a new code segment; helps with linking

# For this code performance is not an issue.  Make it small.


memory_model = -ms
compile_options = -0 $(memory_model) -oh -ok -os -s -oa -ei -zp2 -zpw -we

objs = pacman.obj

all : clean pacman.exe

clean : .symbolic
  @del pacman.exe
  @del *.obj
  @del *.map

.cpp.obj :
  wpp $[* $(compile_options)

pacman.exe : $(objs)
  wlink system dos option map option eliminate option stack=4096 name $@ file *.obj
