# Для сборки из под Windows 10 версии игры для DOS, Winfows 98, Windows XP, Windows 10 
# с помащью Open Watcom 1.9  http://www.openwatcom.org/
# чтоб собрать под DOS вам нужен mTCP http://brutmanlabs.org/mTCP/ 
# (но нужные исходники я уже положил в проект в папки TCPINC и TCPLIB)
#
# чтоб собрать все надо запустить: 
# > wmake
#
# чтоб версию под DOS собрать:
# > wmake pacman.exe
#
# для запуска из под Windows версии для DOS можно использовать DOSBox-X
# ниже пример запуска для случая есть файл конфига лежит тут: C:\ne2000.conf 
# а PACMAN.EXE по пути  C:\PACMAN
# C:\>DOSBox-X -conf ne2000.conf 
#
#
# чтоб версию под Windows собрать
#> wmake wpacman.exe 
#

# заголовочные файлы библиотек из проекта mTCP необходимые для сборки под DOS
tcp_h_dir = TCPINC\

# исходники библиотек из проекта mTCP необходимые для сборки под DOS
tcp_c_dir = TCPLIB\

# заголовочные файлы библиотек из проекта mTCP необходимые для сборки под DOS
common_h_dir = INCLUDE\

# модель памяти при сборке под DOS
memory_model = -mc

# опции компиляции под DOS
compile_options = -0 $(memory_model) -DCFG_H="pacman.cfg" -oh -os -s -zp2 -zpw -we

# опции компиляции под DOS - пути к исходникам и заголовочным файлам
compile_options += -i=$(tcp_h_dir) -i=$(common_h_dir)

# имена объектных файлов которые нужно получить в процессе сборки под DOS
tcpobjs = packet.obj arp.obj eth.obj ip.obj tcp.obj tcpsockm.obj udp.obj utils.obj dns.obj timer.obj ipasm.obj trace.obj

# имя объектного файла игры pacman для DOS
objs = pacman.obj

# собираем из под Windows исполняемые файлы для DOS, Windows, Linux с удалением файлов прошлой сборки
all : clean pacman.exe wpacman.exe

# удалить все фалы сборки
clean : .symbolic
  @del pacman
  @del pacman.exe
  @del wpacman.exe
  @del *.obj
  @del *.map
  @del *.o

patch : .symbolic
  ..\..\utils\ptach pacman.exe pacman.map $(memory_model)

.asm : $(tcp_c_dir)

.cpp : $(tcp_c_dir)

.asm.obj :
  wasm -0 $(memory_model) $[*

.cpp.obj :
  wpp $[* $(compile_options)

# сборка для DOS
# Нужен openwatcom 1.9
# запустить после сборки можно так: dosbox-x -conf ne2000.conf
pacman.exe: $(tcpobjs) $(objs)
  wlink system dos option map option eliminate option stack=4096 name $@ file *.obj

# сборка для Windows 98, Windows XP, Windows 10
# Нужен openwatcom 1.9
# запустить после сборки можно так: wpacman.exe
wpacman.exe:
  wcl386 -l=nt_win ws2_32.lib -bt=nt wpacman.cpp
